classDiagram
    class Persona {
        - Nombre : string
        - ApellidoPaterno : string
        - ApellidoMaterno : string
        - Genero : string
        - Edad : int
        - Usuario : string
        - Contrasena : string
        <<entity>>
    }

    class Jugador {
        - Saldo : float
        - Apuestas : list
        + ConsultarSaldo() : float
        + ActualizarSaldo(monto : float) : float
        + TieneSaldoSuficiente(monto : float) : bool
        + AgregarApuesta(ap : dict) : void
        + ObtenerHistorial() : list
        + RegistrarApuesta(monto: float, tipo: string, resultado: any) : void
        <<entity>>
    }

    class Administrador {
        - NivelAcceso : int
        + GenerarReporte() : string
        + GestionarJugadores() : string
        <<entity>>
    }

    class GestionJugadores {
        - Jugadores : list<Jugador>
        + AgregarJugador(j : Jugador) : void
        + BuscarPorCredenciales(usuario : string, contrasena : string) : Jugador
        + ExisteUsuario(usuario : string) : bool
        + ObtenerTodos() : list<Jugador>
        <<service>>
    }

    class Validador {
        + Validador(dato, tipo, mensajeError, restriccion) : any
        + ValidarMontoPositivo(monto: float) : bool
        + ValidarNumeroRuleta(numero: int) : bool
        + ValidarNumerosDado(numeros: list) : bool
        <<utility>>
    }

    class Apuesta {
        - Jugador : Jugador
        - Monto : float
        - Tipo : string
        - Resultado : any
        - Bono : float
        <<entity>>
    }

    Persona <|-- Jugador
    Persona <|-- Administrador
    GestionJugadores "1" o-- "*" Jugador : gestiona
    Jugador "1" o-- "*" Apuesta : realiza
    Validador <.. Jugador : usa
    Validador <.. GestionJugadores : usa
    Validador <.. Apuesta : valida

